### Create one passenger
POST http://localhost:9004/passengers/1/1

### Create passenger with different tripId
POST http://localhost:9004/passengers/2/1

### Get one passenger
GET http://localhost:9004/passengers/1/1

### Update one passenger
PUT http://localhost:9004/passengers/1/1
Content-Type: application/json

{
  "user_id": 1,
  "trip_id": 1,
  "status": "AcCePtEd"
}

### Delete one passenger
DELETE http://localhost:9004/passengers/1/1

### Get all trips where userId is passenger
GET http://localhost:9004/passengers/users/1

### Delete all trips from user where he is passenger
DELETE http://localhost:9004/passengers/users/1

### Get all passengers of a trip
GET http://localhost:9004/passengers/1

### Delete all passengers of a trip
DELETE http://localhost:9004/passengers/1