openapi: 3.0.3
info:
  title: ChattyCar notification service
  version: 1.0.0
servers:
  - url: 'https://localhost:9005/'
    description: Notifications service
components:
  schemas:
    notification:
      type: object
      properties:
        id_notification:
          type: integer
        id_user:
          type: integer
        id_trip:
          type: integer
        is_on:
          type: boolean
      example:
        id_notification: 1
        id_user: 1
        id_trip: 2
        is_on : false

paths:
  /notifications:
    post:
      summary: create a notification for a user
      requestBody:
        description: id_user and id_trip
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/notification'
      responses:
        409:
          description: user is already added to the trip
        201:
          description: notification added to the user

  /notifications/{id_user}:
    get:
      parameters:
        - name: id_user
          in: path
          description: id of a user
          required: true
          schema:
            type: integer
            example: 1
          style: simple
      summary: get notification for this user
      responses:
        404:
          description: no notification found
        200:
          description: find notifications for the trips of this users
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/notification"
    delete:
      parameters:
          - name: id_user
            in: path
            description: id of a user
            required: true
            schema:
              type: integer
              example: 1
            style: simple
      summary: delete a user's notification
      responses:
        404:
          description: notification does not exist
        200:
          description: delete all the notification associated to user

  /notifications/{id_trip}:
    delete:
      parameters:
        - name: id_trip
          description: id of a trip
          required: true
          schema:
            type: integer
            example: 2
          style: simple
      summary: delete notifications associated to a trip
      responses:
        404:
          description: notification does not exist
        200:
          description: delete all the notifications associated to trip