### Create notification
POST http://localhost:9005/notifications
Content-Type: application/json

{
  "user_id" : 2,
  "trip_id" : 1
}

### Get all notification from a user
GET http://localhost:9005/notifications/1

### Delete all notifications for a user
DELETE http://localhost:9005/notifications/1

### Delete all notifications associated to a trip
DELETE http://localhost:9005/notification/2
