openapi: 3.0.3
info:
  title: ChattyCar distance service
  description: ChattyCar distance service
  version: 1.0.0
servers:
  - url: 'http://localhost:9006'
    description: Development server
paths:
  /distance/{origin_latitude}/{origin_longitude}/{destination_latitude}/{destination_longitude}:
    parameters:
      - name: origin_latitude
        in: path
        required: true
        description: origin latitude of the trip
        schema:
          type: number
          example: 50.4.451009
      - name: origin_longitude
        in: path
        required: true
        description: origin longitude of the trip
        schema:
          type: number
          example: 47.4.451009
      - name: destination_latitude
        in: path
        required: true
        description: destination latitude of the trip
        schema:
          type: number
          example: 50.4.451009
      - name: destination_longitude
        in: path
        required: true
        description: destination longitude of the trip
        schema:
          type: number
          example: 47.4.451009
    get:
      summary: Compute the distance between two positions
      responses:
        400:
          description: Missing parameter
        200:
          description: The distance was successfully calculated
          content:
            text/plain:
              schema:
                type: number
                example: 155.2
